name: HanCommandBlocker
version: '${project.version}'
main: online.bingulhan.commandblocker.CommandBlocker
authors: [ BingulHan ]
commands:
  cb:
    description: Main command
    aliases: ["commandblocker"]
